### ISSUE TITLE
Issue with _docs/tasks/traffic-management/ingress.md

### ISSUE THREAD

**Issue by adityats2020** [istio/istio.github.io#1058]
Following the wiki, it looks like I have to create two ingresses to be able to allow http and https access.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: secure-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  tls:
    - secretName: istio-ingress-certs # currently ignored
  rules:
  - http:
      paths:
      - path: /status/.*
        backend:
          serviceName: httpbin
          servicePort: 8000
      - path: /delay/.*
        backend:
          serviceName: httpbin
          servicePort: 8000
```

This ensures access to httpbin with tls termination at istio ingress.
`kubectl describe ingress secure-ingress` does show up both ports 80 and 443.
But, I have to create the following ingress as well so as to be able to access using http.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - http:
      paths:
      - path: /status/.*
        backend:
          serviceName: httpbin
          servicePort: 8000
      - path: /delay/.*
        backend:
          serviceName: httpbin
          servicePort: 8000
```

When I tested using two ingresses as above using nginx-ingress, the access for the service get disrupted as both the ingress have the same rules for the service (i.e. http). I just need to write one ingress with `tls` and that took care of both http and https.

Is this the behavior with istio ingress or am I missing something?
