### ISSUE TITLE
istio mc does not work

### ISSUE THREAD

**Issue by gyliu513** [istio/istio.github.io#1235]
I deployed @sdake 's demo at https://github.com/istio/istio.github.io/pull/1217#issuecomment-385999899 , but found that it does not work. The request cannot goes to `reviews-v3`.

After I create the route rules as follows, product page info report error.

```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: reviews-default
spec:
  destination:
    name: reviews
  precedence: 1
  route:
  - labels:
      version: v3
    weight: 100
```

![image](https://user-images.githubusercontent.com/4461983/39565383-4d7b46aa-4eea-11e8-9e14-5b2faeb6c5d6.png)

serivcegraph has no info for `reviews-v3`
![image](https://user-images.githubusercontent.com/4461983/39565451-8ce9f660-4eea-11e8-9740-6f5fef2d28ef.png)

I also checked logs based on @john-a-joyce and @tiswanso at https://github.com/istio/istio.github.io/pull/1217#issuecomment-386241278 , but did not found issues.

/cc @sdake any comments for this?
