### ISSUE TITLE
Issue with _docs/samples/bookinfo.md

### ISSUE THREAD

**Issue by mukundha** [istio/istio.github.io#126]
jsonpath fails when i run this -
`export GATEWAY_URL=$(kubectl get po -l istio=ingress -o jsonpath={.items[0].status.hostIP}):$(kubectl get svc istio-ingress -o jsonpath={.spec.ports[0].nodePort})`

is this `istio=ingress` correct?

**Comment by frankbu** [comment]
It should work, `istio=ingress` is correct.
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-ingress
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        alpha.istio.io/sidecar: ignore
      labels:
        istio: ingress
    ...
```
