### ISSUE TITLE
Incorrect ingress configuration in basic authentication policy example

### ISSUE THREAD

**Issue by m-eaton** [istio/istio.github.io#1896]
In this [section](https://preliminary.istio.io/docs/tasks/security/authn-policy.html#setup-end-user-authentication) the sample ingress configuration uses the old Kubernetes ingress API, which was deprecated in Istio v0.8. 

Ingress should be configured with a Gateway and Virtual Service resource, as described [here](https://preliminary.istio.io/docs/tasks/traffic-management/ingress/#configuring-ingress-using-an-istio-gateway).

A sample configuration which works:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
  namespace: foo 
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
  namespace: foo 
spec:
  hosts:
  - "*"
  gateways:
  - httpbin-gateway
  http:
  - route:
    - destination:
        port:
          number: 8000
        host: httpbin.foo.svc.cluster.local 
```

Note that this bug also exists in the Istio v0.8 [docs](https://istio.io/docs/tasks/security/authn-policy/#setup-end-user-authentication)
