### ISSUE TITLE
Issue with docs/tasks/traffic-management/request-routing/index.md

### ISSUE THREAD

**Issue by phanibalaji** [istio/istio.github.io#2203]
Hi,

Without the corresponding DestinationRules defined for the VirtualServices listed, the routing does NOT work as I tested. Only when I create a DestinationRule, for example, for **review** virtual service it works. The below virtualservice along with the DestinationRule when applied routes to **review-v2** service. Moreover we also need to specify **ISTIO_MUTUAL** in destination rule to make the virtual service work if mTLS is enabled.

```
cat << EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
  - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: v3
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews
spec:
  host: reviews
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3
EOF
```

Will you be able to change the docs appropriately if my understanding is correct??
