### ISSUE TITLE
No grafana install steps in /docs/tasks/telemetry/using-istio-dashboard/

### ISSUE THREAD

**Issue by rvennam** [istio/istio.github.io#2425]
https://istio.io/docs/tasks/telemetry/using-istio-dashboard/ says "As part of this task, you will install the Grafana Istio add-on", but no install steps are outlined. 

Grafana is not installed by default when installed using helm:
https://istio.io/docs/setup/kubernetes/helm-install/ Option 1
```
helm template install/kubernetes/helm/istio --name istio --namespace istio-system > $HOME/istio.yaml
kubectl create namespace istio-system
kubectl apply -f $HOME/istio.yaml
```

**Comment by rvennam** [comment]
Same issue with servicegraph https://istio.io/docs/tasks/telemetry/servicegraph/

**Comment by sjdweb** [comment]
Hey, hit this too.

```bash
$ helm upgrade --recreate-pods --namespace istio-system --set grafana.enabled=true istio install/kubernetes/helm/istio
```

grafana.enabled is set to `false` in the default values.

Although I'm not yet seeing any stats in grafana.

**Comment by missourian55** [comment]
I had the same problem. However, scraped all Grafana related configurations from `istio-demo.yaml` and manually applied to the cluster to see the dashboard.

```
---
# Source: istio/charts/grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-grafana-custom-resources
  namespace: istio-system
  labels:
    app: istio-grafana
    chart: grafana-1.0.1
    release: RELEASE-NAME
    heritage: Tiller
    istio: grafana
data:
  custom-resources.yaml: |-    
    apiVersion: authentication.istio.io/v1alpha1
    kind: Policy
    metadata:
      name: grafana-ports-mtls-disabled
      namespace: istio-system
    spec:
      targets:
      - name: grafana
        ports:
        - number: 3000
  run.sh: |-    
    #!/bin/sh
    
    set -x
    
    if [ "$#" -ne "1" ]; then
        echo "first argument should be path to custom resource yaml"
        exit 1
    fi
    
    pathToResourceYAML=${1}
    
    /kubectl get validatingwebhookconfiguration istio-galley 2>/dev/null
    if [ "$?" -eq 0 ]; then
        echo "istio-galley validatingwebhookconfiguration found - waiting for istio-galley deployment to be ready"
        while true; do
            /kubectl -n istio-system get deployment istio-galley 2>/dev/null
            if [ "$?" -eq 0 ]; then
                break
            fi
            sleep 1
        done
        /kubectl -n istio-system rollout status deployment istio-galley
        if [ "$?" -ne 0 ]; then
            echo "istio-galley deployment rollout status check failed"
            exit 1
        fi
        echo "istio-galley deployment ready for configuration validation"
    fi
    sleep 5
    /kubectl apply -f ${pathToResourceYAML}

---
---
# Source: istio/charts/grafana/templates/create-custom-resources-job.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-grafana-post-install-account
  namespace: istio-system
  labels:
    app: istio-grafana
    chart: grafana-1.0.1
    heritage: Tiller
    release: RELEASE-NAME
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: istio-grafana-post-install-istio-system
  labels:
    app: istio-grafana
    chart: grafana-1.0.1
    heritage: Tiller
    release: RELEASE-NAME
rules:
- apiGroups: ["authentication.istio.io"] # needed to create default authn policy
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: istio-grafana-post-install-role-binding-istio-system
  labels:
    app: istio-grafana
    chart: grafana-1.0.1
    heritage: Tiller
    release: RELEASE-NAME
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-grafana-post-install-istio-system
subjects:
  - kind: ServiceAccount
    name: istio-grafana-post-install-account
    namespace: istio-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: istio-grafana-post-install
  namespace: istio-system
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app: istio-grafana
    chart: grafana-1.0.1
    release: RELEASE-NAME
    heritage: Tiller
spec:
  template:
    metadata:
      name: istio-grafana-post-install
      labels:
        app: istio-grafana
        release: RELEASE-NAME
    spec:
      serviceAccountName: istio-grafana-post-install-account
      containers:
        - name: hyperkube
          image: "quay.io/coreos/hyperkube:v1.7.6_coreos.0"
          command: [ "/bin/bash", "/tmp/grafana/run.sh", "/tmp/grafana/custom-resources.yaml" ]
          volumeMounts:
            - mountPath: "/tmp/grafana"
              name: tmp-configmap-grafana
      volumes:
        - name: tmp-configmap-grafana
          configMap:
            name: istio-grafana-custom-resources
      restartPolicy: OnFailure

---
---
# Source: istio/charts/grafana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: istio-system
  annotations:
  labels:
    app: grafana
    chart: grafana-1.0.1
    release: RELEASE-NAME
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: grafana

---
---
# Source: istio/charts/grafana/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  namespace: istio-system
  labels:
    app: grafana
    chart: grafana-1.0.1
    release: RELEASE-NAME
    heritage: Tiller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      containers:
        - name: grafana
          image: "gcr.io/istio-release/grafana:1.0.2"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /login
              port: 3000
          env:
          - name: GRAFANA_PORT
            value: "3000"
          - name: GF_AUTH_BASIC_ENABLED
            value: "false"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: Admin
          - name: GF_PATHS_DATA
            value: /data/grafana
          resources:
            requests:
              cpu: 10m
            
          volumeMounts:
          - name: data
            mountPath: /data/grafana
      affinity:      
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - ppc64le
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - s390x
      volumes:
      - name: data
        emptyDir: {}

---
```

**Comment by kgoralski** [comment]
for EKS I recommend this and `1.0.0.`
```
helm upgrade --recreate-pods --namespace istio-system --set grafana.enabled=true \
             --set global.configValidation=false \
             --set sidecarInjectorWebhook.enabled=false \
             istio \
             install/kubernetes/helm/istio
```

**Comment by linsun** [comment]
yes the recommendation is to enable it manually via helm upgrade by setting grafana.enabled=true

**Comment by rlnrln** [comment]
And if we don't use Helm?  For example, if we want to add this addon to our GKE cluster with Google-managed Istio enabled?

Please consider supplying both pure kubectl yaml files as well as hell config. They both both have legitimate use cases.

**Comment by wayne-o** [comment]
> Documentation has been updated to:
> 
> 1. Add grafana add-on to prereqs in the [Visualizing Metrics with Grafana](https://istio.io/docs/tasks/telemetry/using-istio-dashboard/) page
> 2. Add information to the [helm install page](https://istio.io/docs/setup/kubernetes/helm-install/) about add-ons

Am I missing somthing? I can't see anything on those pages about adding grafana?

w

**Comment by jpatokal** [comment]
> And if we don't use Helm? For example, if we want to add this addon to our GKE cluster with Google-managed Istio enabled?

You can create a new Kubernetes manifest with Grafana enabled, then apply that to your GKE-managed Istio:
```
helm template --set grafana.enabled=true --namespace istio-system \
              install/kubernetes/helm/istio >istio.yaml
kubectl apply -f istio.yaml
```
Beware that this will also restart all Istio services using the default configurations.  To avoid this, you can edit `istio.yaml` to include only those sections where Source: references grafana.  (There's probably an easier way to do this...)

**Comment by markserrano915** [comment]
I got the same issue as with the original poster.

As a context I installed `istio-1.1.0-rc.0` via Helm with the following commands:
```
helm install install/kubernetes/helm/istio-init --name istio-init --namespace istio-system
helm install install/kubernetes/helm/istio --name istio --namespace istio-system
```
Then I played around with https://istio.io/docs/tasks/telemetry/.

Then I found Grafana and Service Graph were not installed and disabled by default in the Helm chart.

**values.yaml**
```
#
# addon grafana configuration
#
grafana:
  enabled: false
....
...
#
# addon servicegraph configuration
#
servicegraph:
  enabled: false
```

I updated those values to **true**. Then I run the following helm upgrade command:

```
helm upgrade istio install/kubernetes/helm/istio
```

Grafana and Service Graph are now installed and working as expected.
