### ISSUE TITLE
Document how to disable auto sidecar injection for a given namespace

### ISSUE THREAD

**Issue by linsun** [istio/istio.github.io#648]
This is a quite common scenario... Looking through the docs I can't find how to do this.  I ended up finding an example in the test.  Seems this is possible via InjectionPolicyEnabled:

https://github.com/istio/pilot/blob/master/platform/kube/inject/inject_test.go#L230

cc @ayj @gyliu513

**Comment by gyliu513** [comment]
@linsun The `InjectionPolicyEnabled` is a global policy and you have to use the annotation of `sidecar.istio.io/inject` to decide inject or not for each application, I think that this is not convenient as the end user need to update all of the applications that do not want injection, +1 to adding a new parameter of excluding some namespaces which does not want to inject data. 

@ayj what do you think?

**Comment by linsun** [comment]
@gyliu513 thanks for correcting me on that!  My wishful thinking... 

@ayj would you support such effort?  We'd be happy to add such function as it 'd be extremely useful to control this on a namespace basis.

**Comment by dcberg** [comment]
The docs do describe how to configure namespaces for injection and how to use the annotation to inject or reject the sidecar injection on a per deployment basis.

https://istio.io/docs/setup/kubernetes/sidecar-injection.html#configuration-options

The main problem I hit is that various kube providers use namespaces for administrative purposes other than `kube-system`. It is not realistic to assume that these providers would use the annotation for every deployment to restrict the istio injection from being applied.

There definitely needs to be a way to configure istio injection to ignore namespaces.

**Comment by linsun** [comment]
@ayj how about adding an ignored-namespaces list in the initializer config, e.g.
`ignored-namespaces: [""]`  with a list of namespaces to exclude in the istio-inject configmap?  The list will be in addition to the current 3 namespaces that are being excluded.

**Comment by ayj** [comment]
Excluding specific namespaces is possible through [ignoredNamespaces](https://github.com/istio/pilot/blob/d2b0cedf57ef1ccc26f3d2a530274dec3fa1e07f/platform/kube/inject/initializer.go#L42). You could extend this list via the ConfigMap. This is probably okay for administrative namespaces but may not scale as a general purpose mechanism for user-created namespaces.

**Comment by dcberg** [comment]
@ayj could we set it up where we could add an annotation to a namespace to ignore it from istio annotation? This would make it easier to manage and would provide the ability to annotate either a deployment or at the namespace level to ignore all within the namespace.

Thoughts?

**Comment by ayj** [comment]
See https://github.com/kubernetes/kubernetes/issues/49048#issuecomment-315892114 for similar suggestions as it relates to the k8s `InitializerConfiguration` itself.

Per-namespace annotations could work. You'd want to define precedence rules w.r.t global and per-deployment policy. This will be further complicated if we want to restrict per-namespace/deployment overrides for security policy.

**Comment by gyliu513** [comment]
@ayj we do want to use the  [ignoredNamespaces](https://github.com/istio/pilot/blob/d2b0cedf57ef1ccc26f3d2a530274dec3fa1e07f/platform/kube/inject/initializer.go#L42) and extend this list via the ConfigMap. But even if want extend it via ConfigMap, we still need to create a PR to introduce the `ignoredNamespaces` to configMap which will be as following:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-inject
  namespace: istio-system
data:
  config: |-
    policy: "enabled"
    ignoredNamespaces: [""] # everything, aka v1.NamepsaceAll, aka cluster-wide
    namespaces: [""] # everything, aka v1.NamepsaceAll, aka cluster-wide
    initializerName: "sidecar.initializer.istio.io"
    params:
      initImage: gcr.io/istio-testing/proxy_init:a8dec7b84d253b3e9d532090e2e150175b991211
      proxyImage: gcr.io/istio-testing/proxy_debug:a8dec7b84d253b3e9d532090e2e150175b991211
      verbosity: 2
      version: a8dec7b84d253b3e9d532090e2e150175b991211
      meshConfigMapName: istio
      imagePullPolicy: IfNotPresent
      debugMode: true
```

For istio initializer, I think that it is OK for the admin to define which namespaces should be excluded.
