### ISSUE TITLE
CRITICAL: Istio initializer causing timeouts in kube API server

### ISSUE THREAD

**Issue by dcberg** [istio/istio.github.io#660]
I have a situation with the 0.2.7 istio-initializer where I see kube API server timeouts when deploying pods. It appears that the problem happens only in a namespace that is NOT having the sidecar injected. This is very important point. 

Here are the steps to recreate the problem.

1) Install istio-initializer as normal (I installed using the instructions from the 0.2.7 release).
2) Create `istio-demo` namespace.
`kubectl create ns istio-demo`
3) Edit the istio-inject configmap to set a single namespace to enable istio injection.
`kubectl edit istio-inject -n istio-system`
Add `istio-demo` as the injected namespace.
```
apiVersion: v1
data:
  config: |-
    policy: "enabled"
    namespaces: ["istio-demo"] # everything, aka v1.NamepsaceAll, aka cluster-wide
    initializerName: "sidecar.initializer.istio.io"
    params:
      initImage: docker.io/istio/proxy_init:0.2.7
      proxyImage: docker.io/istio/proxy:0.2.7
      verbosity: 2
      version: 0.2.7
      meshConfigMapName: istio
      imagePullPolicy: IfNotPresent
kind: ConfigMap
```
4) Save istio-inject configmap.
5) Delete istio-initializer pod to pick up configmap changes.
`kubectl delete pod -n istio-system $(kubectl get pod -n istio-system -l istio=initializer -o jsonpath='{.items[0]..metadata.name}')`
6) Deploy a simple nginx pod in the `istio-demo` namespace. All works fine.
```
kubectl run nginx --image=nginx --replicas=2 -n istio-demo
deployment "nginx" created
```
7) Now try to deploy the same simple nginx pod in the default namespace. You will see a timeout this time.
```
kubectl run nginx --image=nginx --replicas=2
Error from server (Timeout): Timeout: request did not complete within allowed duration
```

The timeout issue is only present when operating within a namespace that is NOT included in the istio injection.

Other information....
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-15T08:51:09Z", GoVersion:"go1.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.4-1+1540c973d4ff9d", GitCommit:"1540c973d4ff9da2d6a204a7709084488a459ed4", GitTreeState:"clean", BuildDate:"2017-10-06T15:08:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

```
kubectl apiversions
Command "apiversions" is deprecated, use "api-versions" instead
admissionregistration.k8s.io/v1alpha1
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1beta1
apps/v1beta1
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
batch/v1
batch/v2alpha1
certificates.k8s.io/v1beta1
config.istio.io/v1alpha2
extensions/v1beta1
networking.k8s.io/v1
policy/v1beta1
rbac.authorization.k8s.io/v1alpha1
rbac.authorization.k8s.io/v1beta1
settings.k8s.io/v1alpha1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1
```

**Comment by linsun** [comment]
@ayj this is the issue I chatted with you about.  Dan sorted out the scenario where it times out on any other namespaces not specified.  Are you aware of anything in initializer or istio-initializer that may cause the namespace not functional?  I'll try recreate this on my system too.

**Comment by dcberg** [comment]
Note....if I delete the istio-initializer deployment then the timeout in the default namespace no longer fails.

**Comment by ayj** [comment]
This was by design to allow multiple initializers managing different sets of namespaces to co-exist in the same cluster. This was necessary given our shared testing infrastructure. Any namespace that is not managed by the initializer (i.e. included in the `namespace` list) is _completely_ ignored by the initializer.

https://github.com/istio/pilot/pull/1437 and `excludeNamespace` could possibly be enhanced to support your use case.

> Note....if I delete the istio-initializer deployment then the timeout in the default namespace no longer fails

Did you delete just the k8s deployment or the entire initializer configuration (i.e. kubectl delete -f istio-initializer.yaml)?

**Comment by dcberg** [comment]
I used `kubectl delete -f istio-initializer.yaml`

I understand the design decision but the implementation cannot cause API server time outs in namespaces that are ignored.

**Comment by linsun** [comment]
I agree, if we can enhance excludeNamespace for this scenario, then we can handle this in istio/pilot#1437.  cc @gyliu513 

As a user, @dcberg can specify namespaces to be included for initializer then everything else will be excluded by the initializer by default.

**Comment by dcberg** [comment]
@linsun I agree that excludeNamespace will be useful but I don't see how that will correct this problem. As a user, if I only want istio applied to a single namespace then I would simply set the one namespace to be used and I would not use `excludeNamespace`. In this scenario all other namespaces in my cluster will be broken due to the istio-initializer.

**Comment by gyliu513** [comment]
@dcberg Please check here https://github.com/gyliu513/jay-work/blob/master/k8s/example/kube-initializer-tutorial/medium-article.md#troubleshooting for how to troubleshooting such issue.

It was caused by that the initializers was added to your deployment, will check more for this how to fix.

```
initializers:
      pending:
      - name: sidecar.initializer.istio.io
```

**Comment by linsun** [comment]
@gyliu513 thanks, that link is super helpful and seems exactly the issue that Dan hit.

@dcberg the reason we think the excludeNamespace will helpful is that we'll treat all other namespaces that is not specified in the namespaces array as excluded from initialization, similar as how we treat the istio-system, kube-system and kube-public namespaces in 0.2.7.

**Comment by gyliu513** [comment]
@ayj this seems to be a serious issue, the current `initializerConfiguration` is cluster level, even if we exclude some namespaces, there will still be `pending initializers` be injected to the deployment and will cause all deployment cannot work. 

I think it is a kubernetes initializer design issue, we may need to file bugs to kubernetes and work there for a solution, comments?

**Comment by mandarjog** [comment]
@ayj the default behaviour seems to be tailored to our test infra use case. Perhaps we should add a bool option shared_cluster or similar that defaults to "false", so initializer will assume it is the only one running unless specified otherwise.

**Comment by linsun** [comment]
@gyliu513 I'm thinking the namespaces aren't properly excluded because I don't hit such behavior in istio-system namespace, as I deployed grafana, prometheus and zipkin after I installed the initializer.

@mandarjog I agree it is pretty dangerous to design the system around the shared test infra.  I just referenced this issue to the #internal_notice for general awareness.

**Comment by gyliu513** [comment]
@dcberg @linsun @ayj as a workaround for such issue, you may want to set initializers as [] for your deployment as following:

```
metadata:
  initializers:
    pending: []
```

This is an example:
```
[root@ib17b03 ~]# cat gyliu/nginx.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: my-nginx
  name: my-nginx
  namespace: default
  initializers:
      pending: []
spec:
  # replicas: 6
  selector:
    matchLabels:
      run: my-nginx
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - image: nginx:1.8.1
        imagePullPolicy: IfNotPresent
        name: my-nginx
        ports:
        - containerPort: 80
          protocol: TCP
```

I also clarified the behavior here https://github.com/gyliu513/jay-work/blob/master/k8s/example/kube-initializer-tutorial/medium-article.md#deploy-the-sidecar-initializer
