### ISSUE TITLE
Issue with _docs/reference/config/traffic-rules/routing-rules.md

### ISSUE THREAD

**Issue by bobbytables** [istio/istio.github.io#727]
Currently this states:

> Note 1: The keys uri, scheme, method, and authority correspond to URI, protocol scheme (e.g., HTTP, HTTPS), HTTP method (e.g., GET, POST), and the HTTP Host header respectively.

The data attribute bag actually passes these prefixed with a colon (I have no idea why), so if you're writing a RouteRule like this:

```yaml
# omitted for brevity
spec:
  destination:
    name: workspacer
  match:
    request:
      headers:
        authority:
          prefix: bobbytables
  precedence: 100
  route:
  - destination:
      name: dev-workspacer
    weight: 100
```

You'll likely be annoyed when you discover this is your issue:

```diff
      headers:
-        authority:
+        :authority:
          prefix: bobbytables
```
