### ISSUE TITLE
Istio fault injection routing rule from Ingress

### ISSUE THREAD

**Issue by ashth231** [istio/istio.github.io#731]
I am trying to get the fault injection abort rule to work from Ingress ( I use traefik on my local minikube)  with my local application. For instance, say Grafana, 

**Service definition:** 
```
apiVersion: v1
kind: Service
metadata:
  name: myhost-grafana
  labels:
    app: grafana
    chart: grafana-0.1.0
    release: foiled-panda
    heritage: Tiller
spec:
  type: ClusterIP
  # type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: grafana
  selector:
    app: grafana
```

**Ingress:**
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myhost-grafana
  labels:
    app: grafana
    chart: grafana-0.1.0
    heritage: Tiller
  annotations:
      0: "map[kubernetes.io/ingress.class:istio]"
      1: "map[kubernetes.io/ingress.class:traefik]"
spec:
  rules:
    - host: "grafana.local"
      http:
        paths:
          - path: /
            backend:
              serviceName: myhost-grafana
              servicePort: 3000
```

**Istio abort rule:**
```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: deny-route
spec:
  destination:
    name: myhost-grafana
  match:
    source:
      labels:
        app: grafana
  precedence: 1
  route:
  - weight: 100
  httpFault:
    abort:
      percent: 100
      httpStatus: 403
```
But all I see when I curl is ,
```
$ curl -I http://grafana.local
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Date: Thu, 23 Nov 2017 12:05:47 GMT
Set-Cookie: grafana_sess=195f2cc07373ac95; Path=/; HttpOnly
```

I also tried curl from within the minikube vm with the  endpointIP:port . The output is same. 
May be am missing some configuration. Has someone got this working for your application?  Any help/suggestions would be greatly appreciated.
